# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top-level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property.
---
include:
  - board: nice_nano_v2
    shield: cradio_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: cradio_right
  - board: nice_nano_v2
    shield: settings_reset
